name = "Season 8 Modpack Lite"
author = "kamaii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e956587aaefc504908afb7c08b12b35c9e5d4f6f603bf68bf40e844597aa4145"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
