# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				axolotl = true
				cow = true
				pig = true
				slime = true
				skeleton = true
				llama = true
				iron_golem = true
				bat = true
				rabbit = true
				cat = true
				zombie = true
				armor_stand = true
				drowned = true
				sheep = true
				player = true
				item = true
				turtle = true
				wolf = true
				villager = true
				salmon = true
				zombie_villager = true
				tnt_minecart = true
				polar_bear = true
				horse = true
				cave_spider = true
				cod = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.tconstruct]
				earth_slime = true

			[light_sources.settings.entities.naturalist]
				deer = true
				robin = true
				snail = true
				canary = true
				firefly = true
				bluejay = true
				butterfly = true
				coral_snake = true
				snake = true

			[light_sources.settings.entities.bewitchment]
				ghost = true
				raven = true

			[light_sources.settings.entities.promenade]
				duck = true
				lush_creeper = true

